services:
  - type: web
    name: telegram-battery-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHANNEL_ID
        value: "@tester_avto"
    plan: free
    autoDeploy: true
